[workspace]
members = [
    "nexuszero-crypto",
    "nexuszero-holographic",
    "nexuszero-integration"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
